# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


jobs:
- job: Test
  strategy:
    matrix:
      node_12: 
        node_version: '12.2.0'
      node_10:
        node_version: '10.15.3'
      node_8:
        node_version: '8.16.0'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(node_version)
      displayName: 'Install Node.js'
    - script: |
        yarn
      displayName: 'Install dependencies'
    - script: |
        yarn run ci
      displayName: 'Run CI'

- job: e2e_tests
  strategy:
    matrix:
      jhipster-1:
        TEST_REPOSITORY: 'e2e-jhipster1'
      jhipster-2:
        TEST_REPOSITORY: 'e2e-jhipster1'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.15.3'
      displayName: 'Install Node.js'
    - script: |
        yarn
      displayName: 'Install dependencies'
    - script: |
        node --version
        npm --version
        yarn --version
        yarn run test:prettier-plugin-java test:$(TEST_REPOSITORY)
      displayName: 'Run e2e tests'